apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport-web
  namespace: prod
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 30555
  selector:
    animal: rabbit
    part: mq
  sessionAffinity: None
  type: NodePort