apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: dev
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
    nodePort: 30500
  selector:
    animal: rabbit
    part: mq
  sessionAffinity: None
  type: NodePort