---
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: rabbitmq
      namespace: prod
      labels:
        animal: rabbit
        part: mq
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      replicas: 1
      revisionHistoryLimit: 1
      selector:
        matchLabels:
          animal: rabbit
          part: mq
      template:
        metadata:
          namespace: prod
          labels:
            animal: rabbit
            part: mq
        spec:
          tolerations:
            - key: "node.kubernetes.io/unreachable"
              operator: "Exists"
              effect: "NoExecute"
              tolerationSeconds: 10
            - key: "node.kubernetes.io/not-ready"
              operator: "Exists"
              effect: "NoExecute"
              tolerationSeconds: 10
          containers:
            - name: rabbitmq
              image: rabbitmq:3.8-management
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 5672
                  name: http
                - containerPort: 15672
              env:
                - name: TZ
                  value: Asia/Almaty
                - name: RABBITMQ_DEFAULT_USER
                  value: user
                - name: RABBITMQ_DEFAULT_PASS
                  value: 123456qW
---
    apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq
      namespace: prod
    spec:
      ports:
        - name: http
          targetPort: 15672
          port: 15672
        - name: data
          targetPort: 5672
          port: 5672
      selector:
        animal: rabbit
        part: mq

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: rabbitmq
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/rabbit)$ $1/ redirect;
  #  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: app.citix.me
    http:
      paths:
      - path: /rabbit(/|$)(.*)
        backend:
          service:
            name: rabbitmq
            port:
              number: 15672
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - app.citix.me
    secretName: cert